---

version: "3"

services:

        flask-app:

                build:

                        context: ./

                        dockerfile: ./Dockerfile

                ports:
                        - 5000:5000

                image: silvermadison/average-weather-app.py:1.0

